"use client";

import '@/styles/globals.css'
import Navbar from '@/components/Navbar'
import ProviderSession from '@/components/ProviderSession'
import Head from 'next/head';

import { Provider } from 'react-redux'
import store from './store'

const Rootlayout = ({ children }) => {
  return (
      <Provider store={store}>
        <html lang="en">
          <Head>
            <title>MiabuSusu</title>
            <meta name="A place to share tests with others" content="Generated by create next app" />
            <link rel="icon" href="/assets/logo.png" />
          </Head>
          <body>    
            <ProviderSession>
              <main className='app'>
                <Navbar />
              </main>
              
              <main className='app'>
                {children}
              </main>
            </ProviderSession>
          </body>
        </html>
      </Provider>
  )
}

export default Rootlayout;