# Generated by Django 4.1 on 2022-10-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
