# Generated by Django 4.1 on 2022-10-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_question_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(max_length=1000, unique=True, unique_for_date='publish'),
        ),
    ]
