# Generated by Django 4.1 on 2023-05-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_newuser_user_name_newuser_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newuser",
            old_name="start_date",
            new_name="date_joined",
        ),
        migrations.AddField(
            model_name="newuser",
            name="is_socail_network",
            field=models.BooleanField(default=False),
        ),
    ]
