# Generated by Django 4.1 on 2023-05-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_rename_start_date_newuser_date_joined_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newuser",
            old_name="is_socail_network",
            new_name="is_social_network",
        ),
    ]
