# Generated by Django 4.1 on 2023-06-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessment", "0001_initial"),
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluation",
            name="answer",
            field=models.ManyToManyField(blank=True, to="forum.answer"),
        ),
    ]
