# Generated by Django 4.1 on 2023-06-20 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessment", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluation",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_evaluations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="forum.category",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessment_evaluations",
                to="assessment.course",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="domain",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_evaluations",
                to="assessment.domain",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="establishment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessment_evaluations",
                to="assessment.establishment",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_evaluations",
                to="assessment.level",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assessment.domain",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="establishment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assessment.establishment",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assessment.level",
            ),
        ),
    ]
