# Generated by Django 4.1 on 2023-07-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0008_alter_evaluation_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="abs_url",
        ),
        migrations.RemoveField(
            model_name="image",
            name="path",
        ),
        migrations.RemoveField(
            model_name="image",
            name="public_id",
        ),
        migrations.RemoveField(
            model_name="image",
            name="url",
        ),
        migrations.AddField(
            model_name="image",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
