# Generated by Django 4.1 on 2023-07-18 15:00

import cloudinary_storage.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assessment", "0010_alter_evaluation_content_alter_evaluation_year"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Cour"},
        ),
        migrations.AlterModelOptions(
            name="domain",
            options={"verbose_name": "Domaine"},
        ),
        migrations.AlterModelOptions(
            name="establishment",
            options={"verbose_name": "Etablissement"},
        ),
        migrations.AlterModelOptions(
            name="evaluation",
            options={"verbose_name": "Epreuve"},
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "Image"},
        ),
        migrations.AlterModelOptions(
            name="level",
            options={"verbose_name": "Niveau"},
        ),
        migrations.AddField(
            model_name="image",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_evaluations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur",
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Contenu"),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessment_evaluations",
                to="assessment.course",
                verbose_name="Cours",
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="domain",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_evaluations",
                to="assessment.domain",
                verbose_name="Domaine",
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="establishment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessment_evaluations",
                to="assessment.establishment",
                verbose_name="Etablissement",
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                related_name="assessment_evaluations",
                to="assessment.image",
                verbose_name="Images",
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_evaluations",
                to="assessment.level",
                verbose_name="Niveau",
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="media",
            field=models.FileField(
                blank=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="raw/",
                verbose_name="Media",
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="status",
            field=models.CharField(
                choices=[("draft", "Brouillon"), ("publish", "Publier")],
                default="publish",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="year",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Année-Académique"
            ),
        ),
    ]
