# Generated by Django 4.1 on 2023-08-24 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0011_alter_course_options_alter_domain_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(max_length=1000, verbose_name="Session"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="images/", verbose_name="Lien Image"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.CharField(max_length=1000, verbose_name="Nom"),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessment_evaluations",
                to="assessment.session",
                verbose_name="Session",
            ),
        ),
    ]
