# Generated by Django 4.1 on 2023-08-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0012_session_alter_image_image_alter_image_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="establishment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assessment.establishment",
            ),
        ),
    ]
