# Generated by Django 4.1 on 2022-10-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
