# Generated by Django 4.1 on 2023-07-02 20:59

import cloudinary_storage.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("create_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_update_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("delete_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_replied", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=100)),
                ("create_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("create_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_update_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("delete_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_replied", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Save",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("content", models.TextField()),
                (
                    "slug",
                    models.SlugField(max_length=1000, unique_for_date="publish_at"),
                ),
                ("publish_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("create_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_update_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("delete_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("publish", "Publish")],
                        default="publish",
                        max_length=10,
                    ),
                ),
                (
                    "media",
                    models.FileField(
                        blank=True,
                        storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                        upload_to="raw/",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="images/")),
            ],
            options={
                "ordering": ["-publish_at"],
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=250)),
                ("visit_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-visit_at"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
