# Generated by Django 4.1 on 2023-06-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0003_initial"),
        ("forum", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="evaluations",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_answers",
                to="assessment.evaluation",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="topics",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_answers",
                to="forum.topic",
            ),
        ),
    ]
