# Generated by Django 4.1 on 2023-07-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"ordering": ["-create_at"]},
        ),
    ]
