# Generated by Django 4.1 on 2023-06-30 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_alter_answer_evaluations_alter_answer_topics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="answer",
        ),
    ]
