# Generated by Django 4.1 on 2023-07-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_alter_answer_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={},
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["author"], name="forum_answe_author__46be3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["evaluations"], name="forum_answe_evaluat_4588ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["topics"], name="forum_answe_topics__cc31a4_idx"
            ),
        ),
    ]
